### ISSUE TITLE
Does not work on latest mediawiki 1.27

### ISSUE THREAD

**Issue by bloggy** [herbix/MCRecipe#1]
Hi,
trying to use this on my mediawiki 1.27. Followed your instructions but as soon as I have it uploaded, my mediawiki can not be access anymore, I am getting a blank page.

**Comment by herbix** [comment]
Update:
I deploy MCRecipe in my website and fixed a bug. You could try again and see if it's solved.

> Hi bloggy,
> Currently I'm not able to install mediawiki 1.27. Could you please offer me some detailed information? For example, server log or something.
